service: lwb-express
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
